Tracker:AddLocations("locations/rules.json")
Tracker:AddLocations("locations/chozo.json")
Tracker:AddLocations("locations/phen.json")
Tracker:AddLocations("locations/tallon.json")
Tracker:AddLocations("locations/mines.json")
Tracker:AddLocations("locations/magmoor.json")
Tracker:AddLocations("locations/maps.json")